from flask import Flask, render_template, request, redirect, jsonify, session
import sqlite3
from datetime import datetime
import smtplib
import threading
import time

app = Flask(__name__)
app.secret_key = "pharmacy_secret_2024"

# ---------------- EMAIL ----------------

last_email_sent = []

def send_email(low_items):
    try:
        sender = "your_email@gmail.com"
        password = "your_app_password"
        receiver = "supplier@gmail.com"

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender, password)

        message = "Subject: 🚨 Medicine Reorder Request - Low Stock Alert\n\n"
        message += "Hello Supplier,\n\n"
        message += "We have identified the following medicines running low in stock:\n\n"
        message += "-------------------------------------\n"

        for i, item in enumerate(low_items, start=1):
            message += f"{i}. {item}\n"

        message += "-------------------------------------\n\n"
        message += "Kindly arrange to supply the above items at the earliest.\n\n"
        message += "This is an automated alert generated by the Pharmacy System.\n\n"
        message += "Thank you,\nPharmacy Management System 💊"

        server.sendmail(sender, receiver, message)
        server.quit()
        print("📧 Email sent successfully")

    except Exception as e:
        print("Email error:", e)


# ---------------- LOGIN ----------------

@app.route("/")
def home():
    if session.get("user"):
        return redirect("/dashboard")
    return render_template("login.html")


@app.route("/login", methods=["POST"])
def login():
    username = request.form["username"]
    password = request.form["password"]

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM users WHERE username=? AND password=?", (username, password))
    user = cursor.fetchone()
    conn.close()

    if user:
        session["user"] = username
        return redirect("/dashboard")
    else:
        return render_template("login.html", error="Invalid username or password")


@app.route("/logout")
def logout():
    session.pop("user", None)
    return redirect("/")


# ---------------- DASHBOARD ----------------

@app.route("/dashboard")
def dashboard():
    if not session.get("user"):
        return redirect("/")

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()

    low = 0
    exp = 0
    expired = 0
    total = len(data)

    low_list = []
    exp_list = []

    today = datetime.today().date()

    for m in data:
        try:
            qty = int(m[2])
        except:
            qty = 0

        if qty < 5:
            low += 1
            low_list.append(m[1])

        try:
            exp_date = datetime.strptime(m[3], "%Y-%m-%d").date()
            if exp_date < today:
                expired += 1
            elif (exp_date - today).days <= 7:
                exp += 1
                exp_list.append(m[1])
        except:
            pass

    conn.close()

    return render_template(
        "dashboard.html",
        low=low,
        exp=exp,
        expired=expired,
        total=total,
        low_list=low_list,
        exp_list=exp_list
    )


# ---------------- ADD ----------------

@app.route("/addpage")
def addpage():
    if not session.get("user"):
        return redirect("/")
    return render_template("add_medicine.html")


@app.route("/add", methods=["POST"])
def add():
    try:
        barcode = request.form.get("barcode", "").strip()
        name = request.form.get("name", "").strip()
        quantity = int(request.form.get("quantity", 0))
        expiry = request.form.get("expiry")
        price = request.form.get("price")

        conn = sqlite3.connect("database.db")
        cursor = conn.cursor()

        if barcode:
            cursor.execute("SELECT * FROM medicines WHERE barcode=?", (barcode,))
            existing = cursor.fetchone()

            if existing:
                new_qty = int(existing[2]) + quantity
                cursor.execute("UPDATE medicines SET quantity=? WHERE barcode=?", (new_qty, barcode))
            else:
                cursor.execute(
                    "INSERT INTO medicines (name,quantity,expiry,price,barcode) VALUES (?,?,?,?,?)",
                    (name, quantity, expiry, price, barcode)
                )
        else:
            cursor.execute("SELECT * FROM medicines WHERE name=?", (name,))
            existing = cursor.fetchone()

            if existing:
                new_qty = int(existing[2]) + quantity
                cursor.execute("UPDATE medicines SET quantity=? WHERE name=?", (new_qty, name))
            else:
                cursor.execute(
                    "INSERT INTO medicines (name,quantity,expiry,price) VALUES (?,?,?,?)",
                    (name, quantity, expiry, price)
                )

        conn.commit()
        conn.close()
        return redirect("/stock")

    except Exception as e:
        return f"Error: {e}"


# ---------------- GET MEDICINE BY BARCODE ----------------

@app.route("/get_medicine/<code>")
def get_medicine(code):
    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM medicines WHERE barcode=?", (code,))
    m = cursor.fetchone()
    conn.close()

    if m:
        return jsonify({"found": True, "id": m[0], "name": m[1], "qty": m[2], "price": m[4]})
    else:
        return jsonify({"found": False})


# ---------------- STOCK ----------------

@app.route("/stock")
def stock():
    if not session.get("user"):
        return redirect("/")

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    q = request.args.get("q")
    if q:
        cursor.execute("SELECT * FROM medicines WHERE name LIKE ?", ('%' + q + '%',))
    else:
        cursor.execute("SELECT * FROM medicines")

    data = cursor.fetchall()

    today = datetime.today().date()
    expired = 0
    exp7 = 0
    exp30 = 0
    low = 0

    for m in data:
        try:
            if int(m[2]) < 5:
                low += 1
        except:
            pass

        try:
            exp_date = datetime.strptime(m[3], "%Y-%m-%d").date()
            days = (exp_date - today).days
            if days < 0:
                expired += 1
            elif days <= 7:
                exp7 += 1
            elif days <= 30:
                exp30 += 1
        except:
            pass

    conn.close()
    return render_template("stock.html", medicines=data, expired=expired, exp7=exp7, exp30=exp30, low=low)


# ---------------- LOW STOCK ----------------

@app.route("/lowstock")
def lowstock():
    if not session.get("user"):
        return redirect("/")

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()

    low = [m for m in data if int(m[2]) < 5]
    conn.close()

    return render_template("lowstock.html", data=low)


# ---------------- EXPIRED ----------------

@app.route("/expired")
def expired():
    if not session.get("user"):
        return redirect("/")

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()

    result = []
    today = datetime.today().date()

    for m in data:
        try:
            exp_date = datetime.strptime(m[3], "%Y-%m-%d").date()
            if exp_date < today:
                result.append(m)
        except:
            pass

    conn.close()
    return render_template("expired.html", data=result)


# ---------------- EDIT ----------------

@app.route("/edit/<int:id>")
def edit(id):
    if not session.get("user"):
        return redirect("/")

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM medicines WHERE id=?", (id,))
    data = cursor.fetchone()
    conn.close()

    return render_template("edit.html", m=data)


@app.route("/update", methods=["POST"])
def update():
    id = request.form["id"]
    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE medicines SET name=?, quantity=?, expiry=?, price=? WHERE id=?",
        (request.form["name"], request.form["quantity"], request.form["expiry"], request.form["price"], id)
    )
    conn.commit()
    conn.close()
    return redirect("/stock")


# ---------------- DELETE ----------------

@app.route("/delete/<int:id>")
def delete(id):
    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("DELETE FROM medicines WHERE id=?", (id,))
    conn.commit()
    conn.close()
    return redirect("/stock")


# ---------------- ALERTS API ----------------

@app.route("/check_alerts")
def check_alerts():
    global last_email_sent

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()
    conn.close()

    low = []
    exp = []
    today = datetime.today().date()

    for m in data:
        try:
            if int(m[2]) < 5:
                low.append(m[1])
        except:
            pass

        try:
            exp_date = datetime.strptime(m[3], "%Y-%m-%d").date()
            if (exp_date - today).days <= 7:
                exp.append(m[1])
        except:
            pass

    email_status = None

    if low and low != last_email_sent:
        try:
            send_email(low)
            email_status = "success"
            last_email_sent = low.copy()
        except:
            email_status = "error"

    return jsonify({"low": low, "exp": exp, "email_status": email_status})


# ---------------- WHATSAPP ALERT ----------------

@app.route("/whatsapp_alert")
def whatsapp_alert():
    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()
    conn.close()

    low = [m[1] for m in data if int(m[2]) < 5]

    if not low:
        return jsonify({"msg": ""})

    message = "🚨 Low stock alert:\n" + "\n".join(f"• {item}" for item in low)
    return jsonify({"msg": message})


# ---------------- BILLING ----------------

@app.route("/billing")
def billing():
    if not session.get("user"):
        return redirect("/")
    return render_template("billing.html")


@app.route("/checkout", methods=["POST"])
def checkout():
    try:
        items = request.json.get("items", [])
        conn = sqlite3.connect("database.db")
        cursor = conn.cursor()

        for item in items:
            cursor.execute(
                "UPDATE medicines SET quantity = quantity - ? WHERE barcode=?",
                (item["qty"], item["barcode"])
            )

        conn.commit()
        conn.close()
        return jsonify({"success": True})

    except Exception as e:
        return jsonify({"success": False, "error": str(e)})


if __name__ == "__main__":
    app.run(debug=True)
