from flask import Flask, render_template, request, redirect
import sqlite3
from datetime import datetime
import smtplib
import os

IS_RENDER = os.environ.get("RENDER") is not None

# 🔥 ADDED IMPORTS
import threading
import time
if not IS_RENDER:
    import tkinter as tk

app = Flask(__name__)

# ---------------- EMAIL ----------------

last_email_sent = []

def send_email(low_items):
    try:
        sender = "your_email@gmail.com"
        password = "your_app_password"
        receiver = "supplier@gmail.com"

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender, password)

        # 🧠 BUILD SMART CONTENT
        message = "Subject: 🚨 Medicine Reorder Request - Low Stock Alert\n\n"

        message += "Hello Supplier,\n\n"
        message += "We have identified the following medicines running low in stock:\n\n"

        message += "-------------------------------------\n"

        for i, item in enumerate(low_items, start=1):
            message += f"{i}. {item}\n"

        message += "-------------------------------------\n\n"

        message += "Kindly arrange to supply the above items at the earliest.\n\n"

        message += "This is an automated alert generated by the Pharmacy System.\n\n"

        message += "Thank you,\n"
        message += "Pharmacy Management System 💊"

        server.sendmail(sender, receiver, message)
        server.quit()

        print("📧 Email sent successfully")

    except Exception as e:
        print("Email error:", e)


# 🔥 ---------------- CUSTOM NOTIFICATION ----------------

def show_custom_notification(message, alert_type="normal"):

    if not IS_RENDER:
        show_custom_notification(...)

    root = tk.Tk()
    root.overrideredirect(True)
    root.attributes("-topmost", True)

    if alert_type == "low":
        bg = "#3f1d1d"
        border = "#ef4444"
    elif alert_type == "expiry":
        bg = "#3f2f1d"
        border = "#f59e0b"
    else:
        bg = "#1e293b"
        border = "#22c55e"

    width = 320
    height = 120

    screen_width = root.winfo_screenwidth()
    screen_height = root.winfo_screenheight()

    x = screen_width - width - 20
    y = screen_height - height - 60

    root.geometry(f"{width}x{height}+{x}+{y}")
    root.configure(bg=border)

    frame = tk.Frame(root, bg=bg)
    frame.place(x=3, y=3, width=width-6, height=height-6)

    title = tk.Label(frame,
                     text="💊 Pharmacy Alert",
                     font=("Segoe UI", 12, "bold"),
                     bg=bg,
                     fg="white")
    title.pack(anchor="w", padx=10, pady=(10, 0))

    msg = tk.Label(frame,
                   text=message,
                   font=("Segoe UI", 10),
                   bg=bg,
                   fg="#e5e7eb",
                   justify="left",
                   wraplength=280)
    msg.pack(anchor="w", padx=10, pady=5)

    root.after(5000, root.destroy)
    root.mainloop()


# 🔥 ---------------- BACKGROUND ALERT LOOP ----------------

def background_alert_checker():

    while True:
        try:
            conn = sqlite3.connect("database.db")
            cursor = conn.cursor()

            cursor.execute("SELECT * FROM medicines")
            data = cursor.fetchall()

            conn.close()

            low_items = []
            exp_items = []

            today = datetime.today().date()

            for m in data:

                try:
                    if int(m[2]) < 5:
                        low_items.append(m[1])
                except:
                    pass

                try:
                    exp_date = datetime.strptime(m[3], "%Y-%m-%d").date()
                    if (exp_date - today).days <= 7:
                        exp_items.append(m[1])
                except:
                    pass

            # 🔔 SHOW NOTIFICATIONS
            if low_items:
                show_custom_notification(
                    "Low:\n" + ", ".join(low_items),
                    "low"
                )

            if exp_items:
                show_custom_notification(
                    "Expiry:\n" + ", ".join(exp_items),
                    "expiry"
                )

        except Exception as e:
            print("Alert error:", e)

        time.sleep(10)


# ---------------- LOGIN ----------------

@app.route("/")
def home():
    return redirect("/login")


@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":
        username = request.form["username"]
    password = request.form["password"]

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM users WHERE username=? AND password=?",
        (username, password)
    )

    user = cursor.fetchone()
    conn.close()

    if user:
        return redirect("/dashboard")
    else:
        return render_template("login.html", error="Invalid Login")


# ---------------- DASHBOARD ----------------

@app.route("/dashboard")
def dashboard():

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()

    low = 0
    exp = 0
    expired = 0

    low_list = []
    exp_list = []

    today = datetime.today().date()

    for m in data:

        try:
            qty = int(m[2])
        except:
            qty = 0

        if qty < 5:
            low += 1
            low_list.append(m[1])

        try:
            exp_date = datetime.strptime(m[3], "%Y-%m-%d").date()

            if exp_date < today:
                expired += 1

            elif (exp_date - today).days <= 7:
                exp += 1
                exp_list.append(m[1])

        except:
            pass

    conn.close()

    return render_template(
        "dashboard.html",
        low=low,
        exp=exp,
        expired=expired,
        low_list=low_list,
        exp_list=exp_list
    )


# ---------------- ADD ----------------

@app.route("/addpage")
def addpage():
    return render_template("add_medicine.html")

@app.route("/add", methods=["POST"])
def add():

    try:
        barcode = request.form.get("barcode")
        name = request.form.get("name")
        quantity = int(request.form.get("quantity", 0))
        expiry = request.form.get("expiry")
        price = request.form.get("price")

        conn = sqlite3.connect("database.db")
        cursor = conn.cursor()

        if barcode:

            cursor.execute(
                "SELECT * FROM medicines WHERE barcode=?",
                (barcode,)
            )

            existing = cursor.fetchone()

            if existing:
                old_qty = int(existing[2])
                new_qty = old_qty + quantity

                cursor.execute(
                    "UPDATE medicines SET quantity=? WHERE barcode=?",
                    (new_qty, barcode)
                )

            else:
                cursor.execute(
                    "INSERT INTO medicines (name,quantity,expiry,price,barcode) VALUES (?,?,?,?,?)",
                    (name, quantity, expiry, price, barcode)
                )

        else:

            cursor.execute(
                "SELECT * FROM medicines WHERE name=?",
                (name,)
            )

            existing = cursor.fetchone()

            if existing:
                old_qty = int(existing[2])
                new_qty = old_qty + quantity

                cursor.execute(
                    "UPDATE medicines SET quantity=? WHERE name=?",
                    (new_qty, name)
                )

            else:
                cursor.execute(
                    "INSERT INTO medicines (name,quantity,expiry,price) VALUES (?,?,?,?)",
                    (name, quantity, expiry, price)
                )

        conn.commit()
        conn.close()

        return redirect("/stock")

    except Exception as e:
        return f"Error: {e}"


# ---------------- STOCK ----------------

@app.route("/stock")
def stock():

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    q = request.args.get("q")

    if q:
        cursor.execute("SELECT * FROM medicines WHERE name LIKE ?", ('%' + q + '%',))
    else:
        cursor.execute("SELECT * FROM medicines")

    data = cursor.fetchall()

    conn.close()

    return render_template("stock.html", medicines=data)


# ---------------- LOW STOCK ----------------

@app.route("/lowstock")
def lowstock():

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()

    low = []

    for m in data:
        try:
            if int(m[2]) < 5:
                low.append(m)
        except:
            pass

    conn.close()

    return render_template("lowstock.html", data=low)


@app.route("/whatsapp_alert")
def whatsapp_alert():

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()

    conn.close()

    low = []

    for m in data:
        try:
            if int(m[2]) < 5:
                low.append(m[1])
        except:
            pass

    if not low:
        return {"msg": ""}

    message = "Low stock items:\n" + "\n".join(low)

    return {"msg": message}


@app.route("/expired")
def expired():

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()

    result = []
    today = datetime.today().date()

    for m in data:
        try:
            exp_date = datetime.strptime(m[3], "%Y-%m-%d").date()
            if exp_date < today:
                result.append(m)
        except:
            pass

    conn.close()

    return render_template("expired.html", data=result)


# ---------------- EDIT ----------------

@app.route("/edit/<int:id>")
def edit(id):

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM medicines WHERE id=?", (id,))
    data = cursor.fetchone()

    conn.close()

    return render_template("edit.html", m=data)


@app.route("/update", methods=["POST"])
def update():

    id = request.form["id"]

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute(
        """UPDATE medicines SET name=?, quantity=?, expiry=?, price=? WHERE id=?""",
        (
            request.form["name"],
            request.form["quantity"],
            request.form["expiry"],
            request.form["price"],
            id
        )
    )

    conn.commit()
    conn.close()

    return redirect("/stock")


# ---------------- DELETE ----------------

@app.route("/delete/<int:id>")
def delete(id):

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute("DELETE FROM medicines WHERE id=?", (id,))

    conn.commit()
    conn.close()

    return redirect("/stock")


# ---------------- ALERT API ----------------

@app.route("/check_alerts")
def check_alerts():

    global last_email_sent

    conn = sqlite3.connect("database.db")
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM medicines")
    data = cursor.fetchall()

    conn.close()

    low = []
    exp = []

    today = datetime.today().date()

    for m in data:

        try:
            if int(m[2]) < 5:
                low.append(m[1])
        except:
            pass

        try:
            exp_date = datetime.strptime(m[3], "%Y-%m-%d").date()
            if (exp_date - today).days <= 7:
                exp.append(m[1])
        except:
            pass

    email_status = None

    if low and low != last_email_sent:
        try:
            send_email("Low stock items: " + ", ".join(low))
            email_status = "success"
            last_email_sent = low.copy()
        except:
            email_status = "error"

    return {
        "low": low,
        "exp": exp,
        "email_status": email_status
    }


# ---------------- BILLING ----------------

@app.route("/billing")
def billing():
    return render_template("billing.html")


# 🔥 START APP + NOTIFICATION SYSTEM
if __name__ == "__main__":

    threading.Thread(target=background_alert_checker, daemon=True).start()